//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PathFinder.Trips.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class IntermediatePoint
    {
        public int Id { get; set; }
        public int TripId { get; set; }
        public System.Data.Entity.Spatial.DbGeography Coordinates { get; set; }
        public string FormattedAddress { get; set; }
        public string Name { get; set; }
        public string PlaceId { get; set; }
        public int IsStart { get; set; }
        public int IsEnd { get; set; }
    
        public virtual Trip Trip { get; set; }
    }
}
