//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PathFinder.Trips.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class IntermediatePoint
    {
        public int Id { get; set; }
        public int TripId { get; set; }
        public int PassangerId { get; set; }
        public System.Data.Entity.Spatial.DbGeography Coordinates { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Trip Trip { get; set; }
    }
}
