//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PathFinder.Trips.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trip
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trip()
        {
            this.IntermediatePoints = new HashSet<IntermediatePoint>();
        }
    
        public int Id { get; set; }
        public int DriverId { get; set; }
        public System.DateTime DepartureDate { get; set; }
        public bool WithReturning { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public bool IsRegular { get; set; }
        public decimal Price { get; set; }
        public int Places { get; set; }
        public System.Data.Entity.Spatial.DbGeography StartPoint { get; set; }
        public System.Data.Entity.Spatial.DbGeography EndPoint { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IntermediatePoint> IntermediatePoints { get; set; }
    }
}
